Fix for Issue#1: TypeError: can't access property "click"
TypeError: can't access property "click", this.currentVideovideo.querySelector(...) is null caused by typo 👀